In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.5


In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.linspace(1,10,num=6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [11]:
np.random.rand(2,3)

array([[0.48745202, 0.56428549, 0.12000099],
       [0.56225119, 0.96106126, 0.49177713]])

In [12]:
np.random.randint(5,size=(2,3))

array([[0, 3, 4],
       [0, 2, 2]])

In [13]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [14]:
a=np.array([10,20,30,40,50])
b=np.arange(1,6)
a,b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

In [15]:
a+b

array([11, 22, 33, 44, 55])

In [16]:
a-b

array([ 9, 18, 27, 36, 45])

In [17]:
a*b

array([ 10,  40,  90, 160, 250])

In [18]:
a/b

array([10., 10., 10., 10., 10.])

In [19]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A,B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [20]:
A+B

array([[ 6,  8],
       [10, 12]])

In [21]:
A-B

array([[-4, -4],
       [-4, -4]])

In [22]:
A*B

array([[ 5, 12],
       [21, 32]])

In [23]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [24]:
np.mat(A)*np.mat(B)

matrix([[19, 22],
        [43, 50]])

In [25]:
2*A

array([[2, 4],
       [6, 8]])

In [26]:
A.T

array([[1, 3],
       [2, 4]])

In [27]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
print(a)
np.sin(a)

[10 20 30 40 50]


array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [29]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [30]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [31]:
np.power(a,3)

array([  1000,   8000,  27000,  64000, 125000], dtype=int32)

In [32]:
a=np.array([1,2,3,4,5])
a[0],a[-1]

(1, 5)

In [33]:
a[0:2],a[:-1]

(array([1, 2]), array([1, 2, 3, 4]))

In [34]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
a[0],a[-1]

(array([1, 2, 3]), array([7, 8, 9]))

In [35]:
a[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [36]:
a=np.random.random((3,2))
a

array([[0.11429231, 0.31345393],
       [0.77185377, 0.42542393],
       [0.89141745, 0.31602279]])

In [37]:
a.shape

(3, 2)

In [38]:
a.reshape(2,3)

array([[0.11429231, 0.31345393, 0.77185377],
       [0.42542393, 0.89141745, 0.31602279]])

In [39]:
a

array([[0.11429231, 0.31345393],
       [0.77185377, 0.42542393],
       [0.89141745, 0.31602279]])

In [40]:
a.resize(2,3)

In [41]:
a

array([[0.11429231, 0.31345393, 0.77185377],
       [0.42542393, 0.89141745, 0.31602279]])

In [42]:
a.ravel()

array([0.11429231, 0.31345393, 0.77185377, 0.42542393, 0.89141745,
       0.31602279])

In [43]:
a=np.random.randint(10,size=(3,3))
b=np.random.randint(10,size=(3,3))
a,b

(array([[1, 5, 0],
        [0, 4, 1],
        [2, 1, 7]]),
 array([[1, 9, 4],
        [0, 8, 2],
        [2, 8, 1]]))

In [44]:
np.vstack((a,b))

array([[1, 5, 0],
       [0, 4, 1],
       [2, 1, 7],
       [1, 9, 4],
       [0, 8, 2],
       [2, 8, 1]])

In [45]:
np.hstack((a,b))

array([[1, 5, 0, 1, 9, 4],
       [0, 4, 1, 0, 8, 2],
       [2, 1, 7, 2, 8, 1]])

In [46]:
np.hsplit(a,3)

[array([[1],
        [0],
        [2]]),
 array([[5],
        [4],
        [1]]),
 array([[0],
        [1],
        [7]])]

In [47]:
np.vsplit(a,3)

[array([[1, 5, 0]]), array([[0, 4, 1]]), array([[2, 1, 7]])]

In [48]:
a=np.array(([1,4,3],[6,2,9],[4,7,2]))
a

array([[1, 4, 3],
       [6, 2, 9],
       [4, 7, 2]])

In [49]:
np.max(a,axis=0)

array([6, 7, 9])

In [50]:
np.min(a,axis=1)

array([1, 2, 2])

In [51]:
np.argmax(a,axis=0)

array([1, 2, 1], dtype=int64)

In [52]:
np.argmin(a,axis=1)

array([0, 1, 2], dtype=int64)

In [53]:
np.mean(a,axis=1)

array([2.66666667, 5.66666667, 4.33333333])

In [54]:
np.average(a,axis=0)

array([3.66666667, 4.33333333, 4.66666667])

In [55]:
np.var(a,axis=1)

array([1.55555556, 8.22222222, 4.22222222])

In [56]:
np.std(a,axis=0)

array([2.05480467, 2.05480467, 3.09120617])

In [57]:
#ADVANCED

In [58]:
Z=np.ones((5,5))
Z[1:-1,1:-1]=0
Z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)

In [60]:
Z=np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [61]:
Z=np.zeros((10,10),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [63]:
Z=np.arange(11)
Z[(1<Z)&(Z<=9)]*=-1
Z

array([ 0,  1, -2, -3, -4, -5, -6, -7, -8, -9, 10])

In [64]:
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print("Z1: ",Z1)
print("Z2: ",Z2)
np.intersect1d(Z1,Z2)

Z1:  [3 9 5 6 8 3 1 6 2 4]
Z2:  [0 0 1 3 9 7 1 1 2 8]


array([1, 2, 3, 8, 9])

In [65]:
yesterday=np.datetime64('today','D') - np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D') + np.timedelta64(1,'D')
print("yesterday: ", yesterday)
print("today: ",today)
print("tomorrow: ",tomorrow)

yesterday:  2023-02-20
today:  2023-02-21
tomorrow:  2023-02-22


In [66]:
Z = np.random.uniform(0,10,10)
print("Original value: ",Z)
print ("method 1: ",Z-Z%1)
print ("method 2: ",np.floor(Z))
print ("method 3: ",np.ceil(Z)-1)
print ("method 4: ",Z.astype(int))
print ("method 5: ",np.trunc(Z))

Original value:  [5.82795086 3.36058885 6.33390601 3.07247546 6.39399947 9.73310594
 2.43878577 0.19085902 1.90793361 0.31456828]
method 1:  [5. 3. 6. 3. 6. 9. 2. 0. 1. 0.]
method 2:  [5. 3. 6. 3. 6. 9. 2. 0. 1. 0.]
method 3:  [5. 3. 6. 3. 6. 9. 2. 0. 1. 0.]
method 4:  [5 3 6 3 6 9 2 0 1 0]
method 5:  [5. 3. 6. 3. 6. 9. 2. 0. 1. 0.]


In [67]:
Z=np.zeros((5,5))
Z+=np.arange(1,6)
Z

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [69]:
Z=np.linspace(0,1,6,endpoint=False)[1:]
Z

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

In [70]:
Z=np.random.random(10)
Z.sort()
Z

array([0.2155029 , 0.33960927, 0.35458747, 0.43632308, 0.59801483,
       0.67190816, 0.69772407, 0.71838922, 0.86077772, 0.87721968])

In [71]:
Z=np.array([[7,4,3],[3,1,2],[4,2,6]])
print("Original array: \n",Z)
Z.sort(axis=0)
Z

Original array: 
 [[7 4 3]
 [3 1 2]
 [4 2 6]]


array([[3, 1, 2],
       [4, 2, 3],
       [7, 4, 6]])

In [72]:
Z=np.random.random(5)
print("Original array: ",Z)
Z[Z.argmax()]=0
Z

Original array:  [0.64629799 0.90098747 0.08700162 0.11377616 0.23073582]


array([0.64629799, 0.        , 0.08700162, 0.11377616, 0.23073582])

In [73]:
for dtype in [np.int8, np.int32, np.int64]:
   print("The minimum value of {}: ".format(dtype),np.iinfo(dtype).min)
   print("The maximum value of {}: ".format(dtype),np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print("The minimum value of {}: ".format(dtype),np.finfo(dtype).min)
   print("The maximum value of {}: ".format(dtype),np.finfo(dtype).max)

The minimum value of <class 'numpy.int8'>:  -128
The maximum value of <class 'numpy.int8'>:  127
The minimum value of <class 'numpy.int32'>:  -2147483648
The maximum value of <class 'numpy.int32'>:  2147483647
The minimum value of <class 'numpy.int64'>:  -9223372036854775808
The maximum value of <class 'numpy.int64'>:  9223372036854775807
The minimum value of <class 'numpy.float32'>:  -3.4028235e+38
The maximum value of <class 'numpy.float32'>:  3.4028235e+38
The minimum value of <class 'numpy.float64'>:  -1.7976931348623157e+308
The maximum value of <class 'numpy.float64'>:  1.7976931348623157e+308


In [74]:
Z=np.arange(10, dtype=np.float32)
print(Z)
Z=Z.astype(np.int32, copy=False)
Z

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
Z=np.random.randint(0,10,(5,5))
print("Before：\n",Z)
Z[Z[:,2].argsort()]

Before：
 [[8 8 7 5 8]
 [8 1 4 5 4]
 [0 1 9 7 4]
 [2 2 5 4 4]
 [1 0 2 4 1]]


array([[1, 0, 2, 4, 1],
       [8, 1, 4, 5, 4],
       [2, 2, 5, 4, 4],
       [8, 8, 7, 5, 8],
       [0, 1, 9, 7, 4]])

In [76]:
Z=np.random.uniform(0,1,20)
print("Random array: \n", Z)
z=0.5
m=Z.flat[np.abs(Z - z).argmin()]
m

Random array: 
 [0.70526594 0.68470659 0.29902193 0.82902936 0.27874811 0.74839758
 0.81184762 0.18152469 0.38290092 0.61532777 0.59016569 0.71451533
 0.42007983 0.62199411 0.37832341 0.29621773 0.20416416 0.89473821
 0.44959004 0.10675614]


0.4495900397353184

In [77]:
A=np.arange(25).reshape(5,5)
print(A)
A[[0,1]]=A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [78]:
Z=np.random.randint(0,10,50)
print("Random one-dimensional array: ", Z)
np.bincount(Z).argmax()

Random one-dimensional array:  [8 8 1 1 5 5 1 7 2 1 5 8 8 0 0 7 4 8 4 3 7 9 8 0 4 4 9 6 3 1 8 8 3 3 8 6 5
 5 3 2 1 2 1 3 1 1 4 2 9 3]


1

In [79]:
Z=np.nonzero([1,0,2,0,1,0,4,0])
Z

(array([0, 2, 4, 6], dtype=int64),)

In [81]:
p=3
Z=np.zeros((5,5))
np.put(Z, np.random.choice(range(5*5),p,replace=False),1)
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
X=np.random.rand(3, 3)
print(X)
Y=X-X.mean(axis=1,keepdims=True)
Y

[[0.24358388 0.56754778 0.24417506]
 [0.40300352 0.64209861 0.57835139]
 [0.3952825  0.1878722  0.26825046]]


array([[-0.10818503,  0.21577888, -0.10759385],
       [-0.13814766,  0.10094743,  0.03720022],
       [ 0.11148078, -0.09592952, -0.01555126]])

In [83]:
A=np.random.uniform(0,1,(3,3))
B=np.random.uniform(0,1,(3,3))
print(np.dot(A, B))
np.diag(np.dot(A, B))

[[0.33698374 0.42456567 0.99530297]
 [0.53633308 0.60988241 1.35228595]
 [0.10875472 0.09934165 0.32549819]]


array([0.33698374, 0.60988241, 0.32549819])

In [84]:
np.sum(A * B.T, axis=1)

array([0.33698374, 0.60988241, 0.32549819])

In [85]:
np.sum(A * B.T, axis=1)

array([0.33698374, 0.60988241, 0.32549819])

In [86]:
Z=np.random.randint(1,100,100)
print(Z)
p = 5
Z[np.argsort(Z)[-p:]]

[72 42 47 95 90 57  5 32 42 32 22 93 86 70 84 76 96 71  9 38 28 17 70 25
 90 97 96 47 45 35 24 69 55 83 91 51 17 87  9 35 92  4 57 82 43 79 68 60
 50 28 28 51 84 25 24 59 21  4 67 21 65 98 22  7 60 94 29 34 28 40 67  4
 71 85 43  9 14 18 40 44 31  2 47  8 97 36 45 42 38 51  9 58 27 63 44 20
 34 31 81 46]


array([96, 96, 97, 97, 98])

In [87]:
x=np.random.randint(2,5,5)
print(x)
np.power(x,4)

[2 2 2 4 2]


array([ 16,  16,  16, 256,  16], dtype=int32)

In [88]:
Z=np.random.random((5,5))
print(Z)
np.set_printoptions(precision=2)
Z

[[0.03931938 0.58197284 0.51330432 0.87081583 0.93422721]
 [0.21031881 0.83299136 0.34518504 0.94891145 0.25398564]
 [0.67838354 0.0955566  0.62509598 0.98083464 0.138854  ]
 [0.40536135 0.53509023 0.30952965 0.03207514 0.9041961 ]
 [0.93836598 0.05562962 0.11861273 0.75350965 0.41795436]]


array([[0.04, 0.58, 0.51, 0.87, 0.93],
       [0.21, 0.83, 0.35, 0.95, 0.25],
       [0.68, 0.1 , 0.63, 0.98, 0.14],
       [0.41, 0.54, 0.31, 0.03, 0.9 ],
       [0.94, 0.06, 0.12, 0.75, 0.42]])

In [89]:
Z=np.random.random([5,5])
print(Z)
Z/1e3

[[0.21 0.73 0.1  0.9  0.94]
 [0.91 0.53 0.38 0.01 0.77]
 [0.39 0.59 0.27 0.78 0.45]
 [0.84 0.59 0.28 0.37 0.15]
 [0.91 0.68 0.07 0.02 0.36]]


array([[2.12e-04, 7.27e-04, 1.05e-04, 9.04e-04, 9.45e-04],
       [9.11e-04, 5.32e-04, 3.80e-04, 7.70e-06, 7.70e-04],
       [3.86e-04, 5.90e-04, 2.73e-04, 7.78e-04, 4.48e-04],
       [8.38e-04, 5.87e-04, 2.77e-04, 3.73e-04, 1.54e-04],
       [9.08e-04, 6.81e-04, 7.34e-05, 1.84e-05, 3.56e-04]])

In [90]:
a=np.arange(15)
print(a)
np.percentile(a,q=[25,50,75])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 3.5,  7. , 10.5])

In [92]:
Z=np.random.rand(10,10)
Z[np.random.randint(10,size=5),np.random.randint(10,size=5)]=np.nan
Z

array([[0.92, 0.3 ,  nan, 0.9 , 0.01, 0.41, 0.45, 0.51, 0.1 , 0.73],
       [0.9 , 0.05, 0.62, 0.6 , 0.03, 0.41, 0.62, 0.27, 0.85,  nan],
       [0.45, 0.16, 0.61, 0.4 , 0.32, 0.74,  nan, 0.3 , 0.53, 0.47],
       [0.23, 0.34, 0.85, 0.44, 0.23, 0.33, 0.01, 0.66, 0.93, 0.74],
       [0.85, 0.43, 0.34, 0.92, 0.82, 0.29, 0.38, 0.31, 0.29, 0.53],
       [0.8 , 0.58, 0.27, 0.91, 0.1 , 0.23, 0.18, 0.56, 0.48, 0.99],
       [ nan, 0.6 , 0.69, 0.74, 0.15, 0.89, 0.88, 0.21, 0.72, 0.55],
       [0.49, 0.76, 0.57, 0.25, 0.62, 0.14, 0.42, 0.06, 0.23, 0.85],
       [0.16, 0.49, 0.4 , 0.69, 0.19, 0.64, 0.76, 0.45, 0.79, 0.42],
       [0.46, 0.58, 0.46, 0.6 , 0.24, 0.52, 0.07, 0.49, 0.9 , 0.5 ]])

In [94]:
print("Total number of missing values: \n",np.isnan(Z).sum())
print("Indexes of missing values: \n",np.where(np.isnan(Z)))

Total number of missing values: 
 4
Indexes of missing values: 
 (array([0, 1, 2, 6], dtype=int64), array([2, 9, 6, 0], dtype=int64))


In [96]:
Z[np.sum(np.isnan(Z),axis=1)==0]

array([[0.23, 0.34, 0.85, 0.44, 0.23, 0.33, 0.01, 0.66, 0.93, 0.74],
       [0.85, 0.43, 0.34, 0.92, 0.82, 0.29, 0.38, 0.31, 0.29, 0.53],
       [0.8 , 0.58, 0.27, 0.91, 0.1 , 0.23, 0.18, 0.56, 0.48, 0.99],
       [0.49, 0.76, 0.57, 0.25, 0.62, 0.14, 0.42, 0.06, 0.23, 0.85],
       [0.16, 0.49, 0.4 , 0.69, 0.19, 0.64, 0.76, 0.45, 0.79, 0.42],
       [0.46, 0.58, 0.46, 0.6 , 0.24, 0.52, 0.07, 0.49, 0.9 , 0.5 ]])

In [97]:
Z=np.random.randint(0,100,25).reshape(5,5)
print(Z)
np.unique(Z,return_counts=True)

[[75 72 44 29 27]
 [88  2 32 24 60]
 [45 25 61 98  2]
 [53 13 95 19 45]
 [61 18 17 98 64]]


(array([ 2, 13, 17, 18, 19, 24, 25, 27, 29, 32, 44, 45, 53, 60, 61, 64, 72,
        75, 88, 95, 98]),
 array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2],
       dtype=int64))

In [98]:
Z=np.random.randint(1,4,10)
print(Z)
label_map={1:"car",2:"bus",3:"train"}
[label_map[x] for x in Z]

[1 2 2 3 2 2 1 3 3 3]


['car', 'bus', 'bus', 'train', 'bus', 'bus', 'car', 'train', 'train', 'train']

In [99]:
Z1=np.arange(3)
Z2=np.arange(3,7)
Z3=np.arange(7,10)
Z=np.array([Z1,Z2,Z3])
print(Z)
np.concatenate(Z)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]


C:\Users\M\AppData\Local\Temp\ipykernel_15760\3183290245.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  Z=np.array([Z1,Z2,Z3])


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
a=np.random.randint(100, size=10)
print('Array: ', a)
a.argsort()

Array:  [68 35 65 67 10 48 65  8 99  7]


array([9, 7, 4, 1, 5, 2, 6, 3, 0, 8], dtype=int64)

In [102]:
Z=np.random.randint(1,100,[5,5])
print(Z)
np.amax(Z,axis=1)

[[97 29 36  9 57]
 [ 1 33 73 35 26]
 [61 83 46 27  6]
 [60 90 33  1 40]
 [11 12 64 19 51]]


array([97, 73, 83, 90, 64])

In [103]:
Z=np.random.randint(1,100,[5,5])
print(Z)
np.apply_along_axis(np.min,arr=Z,axis=1)

[[10  6 70 37 92]
 [ 3 94 17 83  3]
 [34 67 98 70  3]
 [35 18 78 48  6]
 [84 20 38 60 19]]


array([ 6,  3,  3,  6, 19])

In [104]:
a=np.array([1, 2])
b=np.array([7, 8])
print(np.sqrt(np.power((8-2),2)+np.power((7-1),2)))
np.linalg.norm(b-a)

8.48528137423857


8.48528137423857

In [105]:
a=np.array([1+2j,3+4j,5+6j])
print("real：",a.real)
print("imaginary：",a.imag)

real： [1. 3. 5.]
imaginary： [2. 4. 6.]


In [106]:
matrix=np.array([[1., 2.],[3., 4.]])
inverse_matrix = np.linalg.inv(matrix)
assert np.allclose(np.dot(matrix,inverse_matrix),np.eye(2))
assert np.allclose(np.dot(matrix,inverse_matrix),np.eye(2))
inverse_matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [107]:
def zscore(x,axis=None):
    xmean=x.mean(axis=axis,keepdims=True)
    xstd=np.std(x,axis=axis,keepdims=True)
    zscore=(x-xmean)/xstd
    return zscore
Z=np.random.randint(10, size=(5,5))
print(Z)
zscore(Z)

[[3 1 0 2 1]
 [2 2 8 0 3]
 [7 4 8 5 7]
 [4 4 5 1 2]
 [3 0 8 9 4]]


array([[-0.26, -1.  , -1.37, -0.63, -1.  ],
       [-0.63, -0.63,  1.57, -1.37, -0.26],
       [ 1.21,  0.1 ,  1.57,  0.47,  1.21],
       [ 0.1 ,  0.1 ,  0.47, -1.  , -0.63],
       [-0.26, -1.37,  1.57,  1.94,  0.1 ]])

In [108]:
def min_max(x,axis=None):
    min=x.min(axis=axis,keepdims=True)
    max=x.max(axis=axis,keepdims=True)
    result=(x-min)/(max-min)
    return result

Z=np.random.randint(10,size=(5,5))
print(Z)
min_max(Z)

[[4 9 5 6 9]
 [0 6 3 4 4]
 [9 9 4 1 0]
 [1 2 3 7 5]
 [9 7 3 4 4]]


array([[0.44, 1.  , 0.56, 0.67, 1.  ],
       [0.  , 0.67, 0.33, 0.44, 0.44],
       [1.  , 1.  , 0.44, 0.11, 0.  ],
       [0.11, 0.22, 0.33, 0.78, 0.56],
       [1.  , 0.78, 0.33, 0.44, 0.44]])

In [109]:
def l2_normalize(v,axis=-1,order=2):
    l2=np.linalg.norm(v,ord=order,axis=axis,keepdims=True)
    l2[l2==0]=1
    return v/l2
Z=np.random.randint(10,size=(5,5))
print(Z)
l2_normalize(Z)

[[8 9 1 0 8]
 [5 6 6 4 1]
 [3 8 2 3 7]
 [5 4 9 2 1]
 [4 4 5 7 9]]


array([[0.55, 0.62, 0.07, 0.  , 0.55],
       [0.47, 0.56, 0.56, 0.37, 0.09],
       [0.26, 0.69, 0.17, 0.26, 0.6 ],
       [0.44, 0.35, 0.8 , 0.18, 0.09],
       [0.29, 0.29, 0.37, 0.51, 0.66]])

In [110]:
Z=np.array([
    [1,2,1,9,10,3,2,6,7],
    [2,1,8,3,7,5,10,7,2],
    [2,1,1,8,9,4,3,5,7]])
np.corrcoef(Z)

array([[ 1.  , -0.06,  0.97],
       [-0.06,  1.  , -0.01],
       [ 0.97, -0.01,  1.  ]])

In [111]:
M=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
w,v=np.linalg.eig(M)
w,v

(array([ 1.61e+01, -1.12e+00, -3.38e-16]),
 matrix([[-0.23, -0.79,  0.41],
         [-0.53, -0.09, -0.82],
         [-0.82,  0.61,  0.41]]))

In [112]:
v*np.diag(w)*np.linalg.inv(v)

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [113]:
Z=np.random.randint(1,10,10)
print(Z)
print(np.diff(Z,n=1))
print(np.diff(Z,n=2))
print(np.diff(Z,n=3))

[7 5 2 1 3 6 1 9 7 4]
[-2 -3 -1  2  3 -5  8 -2 -3]
[ -1   2   3   1  -8  13 -10  -1]
[  3   1  -2  -9  21 -23   9]


In [116]:
Z=np.random.randint(1,10,10)
print(Z)
np.cumsum(Z)

[5 5 7 4 7 2 8 8 6 5]


array([ 5, 10, 17, 21, 28, 30, 38, 46, 52, 57], dtype=int32)

In [117]:
M1=np.array([1,2,3])
M2=np.array([4,5,6])
np.c_[M1,M2]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [118]:
M1=np.array([1,2,3])
M2=np.array([4,5,6])
np.r_[M1,M2]

array([1, 2, 3, 4, 5, 6])

In [119]:
np.fromfunction(lambda i, j: (i + 1) * (j + 1), (9, 9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])